version: 2.1
jobs:
  test-unit:
    docker:
      - image: 'circleci/node:10.16.1-browsers'
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn test:unit