name: CI Test

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '.github/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '14.18.2'
      - name: Bootstrap
        run: yarn bootstrap
      - name: Build
        run: yarn build
      - name: Unit test
        run: yarn test:unit
